name: pahlay yaml learning
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
     - name: pahlaprint
       run: echo "mam love u"
     - name: prinit suyash
       run: echo "suyash/sharad"
  second_job:
    runs-on: windows-latest
    steps:
     - name: print chachu
       run: echo "chachu"
